project_structure:
    build: client/src/artifacts
networks:
  default: development
  development:
    cmd_settings:
      mnemonic: hill law jazz limb penalty escape public dish stand bracket blue jar
dev_deployment_artifacts: true
